@startuml
[*] ---> EncargarProducto : Inicio del Proceso

state EncargarProducto {
    [*] ---> Encargar : Seleccionar Producto
    Encargar ---> Pagar : Confirmar y Pagar
    Pagar ---> PedidoColocado : Pedido Realizado
}

EncargarProducto ---> PedidoColocado

state PedidoColocado {
    [*] ---> ValidarPedido : Verificar Pedido
    ValidarPedido ---> CobrarPago : Confirmar Pago
    CobrarPago ---> PedidoPagado : Pago Completado
}

PedidoColocado ---> PedidoPagado

state PedidoPagado {
    [*] --> ObtenerProducto : Preparar Producto
    ObtenerProducto ---> EnvioUrgente : [urgente] Envío Rápido
    ObtenerProducto ---> EnvioOrdinario : [no urgente] Envío Estándar
    EnvioUrgente ---> PedidoRealizado : Producto Enviado
    EnvioOrdinario ---> PedidoRealizado : Producto Enviado
}

PedidoPagado ---> PedidoRealizado

state PedidoRealizado {
    [*] --> DarCervezas : Premiar Transportistas
    DarCervezas ---> ClienteSatisfecho : Registrar Cliente Satisfecho
    DarCervezas ---> EnviarRecibo : Generar Recibo
    ClienteSatisfecho ----> [*]
    EnviarRecibo ----> [*]
}
@enduml
